name: openapi-generator
version: 0.2.0
github: "frysztak/openapi-generator"
license: BSD3
author: "Sebastian Frysztak"
maintainer: "sebastian@frysztak.dev"
copyright: "2021 Sebastian Frysztak"

extra-source-files:
  - README.md
  - ChangeLog.md

description: OpenAPI client generator

dependencies:
  - base >= 4.7 && < 5
  - text
  - bytestring
  - aeson
  - containers
  - hspec
  - raw-strings-qq
  - lens
  - generic-lens
  - data-default
  - optparse-applicative
  - filepath
  - directory
  - mtl
  - githash

library:
  source-dirs:
    - src

executables:
  openapi-generator:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - openapi-generator

tests:
  spec:
    defaults: hspec/hspec@master
    dependencies:
      - openapi-generator
