name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  stack:
    name: stack / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        stack: ["2.7"]

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/main'
    
    - name: Setup env variables (Linux)
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        echo "extension=" >> $GITHUB_ENV
        echo "filename=openapi-generator-linux-amd64" >> $GITHUB_ENV
        echo "binaryPath=${{ github.workspace }}/artifact/openapi-generator-linux-amd64" >> $GITHUB_ENV

    - name: Setup env variables (MacOS)
      if: startsWith(matrix.os, 'mac')
      run: |
        echo "extension=" >> $GITHUB_ENV
        echo "filename=openapi-generator-macos-amd64" >> $GITHUB_ENV
        echo "binaryPath=${{ github.workspace }}/artifact/openapi-generator-macos-amd64" >> $GITHUB_ENV

    - name: Setup env variables (Windows)
      if: startsWith(matrix.os, 'windows')
      run: |
        echo "extension=.exe" >> $GITHUB_ENV
        echo "filename=openapi-generator-win64.exe" >> $GITHUB_ENV
        echo "binaryPath=${{ github.workspace }}\artifact\openapi-generator-win64.exe" >> $GITHUB_ENV

    - uses: actions/setup-haskell@v1.1.4
      name: Setup Haskell Stack
      with:
        stack-version: ${{ matrix.stack }}

    - uses: actions/cache@v2.1.3
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack

    - name: Install dependencies
      run: |
        stack build --test --bench --no-run-tests --no-run-benchmarks --only-dependencies

    - name: Build
      run: |
        stack build --test --bench --no-run-tests --no-run-benchmarks

    - name: Test
      run: |
        stack test

    - name: Copy binary
      run: |
        stack install
        mkdir -p ${{ github.workspace }}/artifact
        cp $(stack path --local-bin)/openapi-generator${{ env.extension }} ${{ env.binaryPath }}

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.filename }}
        path: ${{ env.binaryPath }}

    - name: Release
      uses: softprops/action-gh-release@v1
      #if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: True
        body_path: ${{ github.workspace }}/ChangeLog.md
        files: ${{ env.binaryPath }}