name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  stack:
    name: stack / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        stack: ["2.7"]

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/main'
    
    - name: Setup OS map
      uses: kanga333/variable-mapper@master
      with:
        key: "${{matrix.os}}"
        map: |
          {
            "ubuntu-latest": {
              "filename": "openapi-generator-linux64"
            },
            "macOS-latest": {
              "filename": "openapi-generator-macos-intel"
            },
            "windows-latest": {
              "filename": "openapi-generator-win64.exe"
            }
          }

    - uses: actions/setup-haskell@v1.1.4
      name: Setup Haskell Stack
      with:
        stack-version: ${{ matrix.stack }}

    - uses: actions/cache@v2.1.3
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack

    - name: Install dependencies
      run: |
        stack build --test --bench --no-run-tests --no-run-benchmarks --only-dependencies

    - name: Build
      run: |
        stack build --test --bench --no-run-tests --no-run-benchmarks

    - name: Test
      run: |
        stack test

    - name: Copy binary
      run: |
        stack install
        mkdir -p ${{ github.workspace }}/artifact
        cp $(stack path --local-bin)/openapi-generator ${{ github.workspace }}/artifact/${{ env.filename }}

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.filename }}
        path: ${{ github.workspace }}/artifact/${{ env.filename }}